import { ShieldAlert } from "lucide-react";

export function ResponsibleAINotice() {
  return (
    <div className="mt-8 rounded-lg border border-border bg-muted/40 p-4 text-xs text-muted-foreground">
      <div className="flex gap-2">
        <ShieldAlert className="h-4 w-4 shrink-0 text-primary" />
        <p>
          <span className="font-semibold text-foreground">Responsible AI Notice: </span>
          This application uses Artificial Intelligence to assist users with workplace
          productivity tasks. AI-generated content may contain inaccuracies and should be
          reviewed and verified before use. Users remain responsible for final decisions,
          communications, schedules, and actions generated by the system.
        </p>
      </div>
    </div>
  );
}
